- name: variables in ansible
  hosts: mongodb
  # this is play level varaibles ,map
  vars:
    COURSE: devops with aws
    TRAINER: siva kumar
    DURATION: 110hrs
  tasks:
  - name: print hello world
    ansible.builtin.debug:
     msg: "i am learning devops"
  - name: print variable values
    ansible.builtin.debug:
     msg: "i am learning {{COURSE}},trainer is {{TRAINER}}, duraion is {{DURATION}}"
