- name: variables from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: enter ur username
    private: false # u can see the value entered on screen
  - name: PASSWORD
    prompt: enter password
    private: true # u can't see the values entered o screen
    tasks:
    - name: printing values
      ansible.builtin.debug:
       msg: "username is: {{USERNAME}},password is: {{PASSWORD}}"